# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoFile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoFile
pod 'FlexibleModelProtocol', '~> 1.1'

end
